default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kadai_tw_development

test:
  <<: *default
  database: kadai_tw_test

production:
  <<: *default
  database: kadai_tw_production
  username: kadai_tw
  password: <%= ENV['KADAI_TW_DATABASE_PASSWORD'] %>
